### ISSUE TITLE
Error with signing in when security key is demanded

### ISSUE THREAD

**Issue by obumnwabude** [sammychinedu2ky/puppeteer-repo-generator#1]
Hi @sammychinedu2ky
Thank you very much for this great package. It is really a nice one having to create GitHub repos directly from the command line.

I however came across a problem while using it. I forked and debugged and realized where the problem was from. The two-factor authentication setting on my Github account demands a security key when logging in, in addition to the OTP. And this is not checked by the code. And the command line's error did not explain that, it said:
`(node:8316) UnhandledPromiseRejectionWarning: Error: No node found for selector:
 #repository_name`

So, I felt like the `repo-gen` could be improved for better error handling and for enabling sign in when the security feature is attached.

Please let me hear from you on this. Thank you
`

**Comment by sammychinedu2ky** [comment]
Thanks alot for taking your time to report this.. I actually made provision for that.. 
Once that is required, all you need to do is to check your email and insert the otp in the command line and click on your enter key to proceed..
I'm sorry I didn't say that in the read me file but I actually added support for that scenario.

**Comment by obumnwabude** [comment]
Yes I saw the provisioning for OTP.

I created a dummy GitHub account and used with `repo-gen` and it created the repo successfully.
I then set two factor authentication in the account and retried and I saw the demanded OTP in my phone and entered it there in the command line, and the repo was created successfully. 

But then I went further to add security key feature in the GitHub account and retried, then saw the problem I had earlier. You may want to add security key feature in your GitHub account two factor authentication settings, when logged in with your phone. Then use `repo-gen` and you'll see what I'm saying.

**Comment by obumnwabude** [comment]
Also, `repo-gen` is really a nice tool. Thank you for it. But please I think it could be better if there was error handling. Like chaining the promises with catch blocks, instead of just using await. And moving to the next step of repo creation only when login promise had resolved (when login was successful).

**Comment by sammychinedu2ky** [comment]
Thanks man, it's true I didn't add support for security keys just otp and normal login fields.. but I'm happy you saw the things that could be worked on.. 
I'm open for a pull request as well.

**Comment by obumnwabude** [comment]
Great then I'll work on it.
And open pull requests.

**Comment by sammychinedu2ky** [comment]
Solved
